### PR TITLE
Update reading

### PR DESCRIPTION
**Pull request by jburel**
* Create basic env
* Fix notebook

### CODE REVIEW

**Comment by pwalczysko** [comment]
reading images day4 works fine in Colab and M1

lgtm

**Review by pwalczysko — APPROVED** [review]

**Review by pwalczysko — CHANGES_REQUESTED** [review]
did not test yet, deleted my previous comment , sorry

**Comment by pwalczysko** [comment]
Works fine on M1 (reading images day4). Colab still testing.

**Comment by pwalczysko** [comment]
``**Run the below if running the plugin in Google Colab**
This cell will allow to select an image from your local machine. 
The image will be uploaded to Google colab.`` -> ``**Run the below if running the plugin in Google Colab**
This cell will allow to select an image from your local machine. You MUST upload a .tiff image.
The image will be uploaded to Google colab.``

I think we have to warn the user not to upload anything else but tiff. ^^^

**Comment by pwalczysko** [comment]
The cell just after the [upload cell](https://github.com/ome/EMBL-EBI-imaging-course-04-2024/pull/9#issuecomment-2061127314) is erroring, although I have changed the name to match the name of the uploaded tiff. I also tried to remove the ``content`` top folder, but still the same error:

```

Figure_2024-03-18_15-05-48.tiff(image/tiff) - 34785482 bytes, last modified: n/a - 100% done

Saving Figure_2024-03-18_15-05-48.tiff to Figure_2024-03-18_15-05-48.tiff

....

image_local = skio.imread("includes/Figure_2024-03-18_15-05-48.tiff", plugin="tifffile")

---------------------------------------------------------------------------

FileNotFoundError                         Traceback (most recent call last)

[<ipython-input-10-474d0d273884>](https://localhost:8080/#) in <cell line: 1>()
----> 1 image_local = skio.imread("includes/Figure_2024-03-18_15-05-48.tiff", plugin="tifffile")

6 frames

/usr/local/lib/python3.10/dist-packages/tifffile/tifffile.py in open(self)
  14471             self._file = os.path.realpath(self._file)
  14472             self._dir, self._name = os.path.split(self._file)
> 14473             self._fh = open(
  14474                 self._file, self._mode, encoding=None
  14475             )  # type: ignore

FileNotFoundError: [Errno 2] No such file or directory: '/content/includes/Figure_2024-03-18_15-05-48.tiff'
```

**Review by pwalczysko — CHANGES_REQUESTED** [review]
Please 
- warn that we need to upload specifically a tiff
- address the problems in Colab when uploading tiff image.

**Comment by jburel** [comment]
You need to specify the name correctly it is ``Figure_2024-03-18_15-05-48.tiff`` not ``includes/Figure_2024-03-18_15-05-48.tiff``

**Comment by pwalczysko** [comment]
> You need to specify the name correctly it is `Figure_2024-03-18_15-05-48.tiff` not `includes/Figure_2024-03-18_15-05-48.tiff`

But this will confuse many: I assumed that I cannot touch the ``include`` containing folder - just to replace the name of the tiff

aha, you added an example ^^^ - this might do

**Comment by pwalczysko** [comment]
```
IndexError                                Traceback (most recent call last)

[/usr/local/lib/python3.10/dist-packages/ipywidgets/widgets/interaction.py](https://localhost:8080/#) in update(self, *args)
    255                     value = widget.get_interact_value()
    256                     self.kwargs[widget._kwarg] = value
--> 257                 self.result = self.f(**self.kwargs)
    258                 show_inline_matplotlib_plots()
    259                 if self.auto_display and self.result is not None:

[<ipython-input-17-e489870d1d01>](https://localhost:8080/#) in update(z)
      6     c = 1
      7     fig = plt.figure(figsize=(10, 10))
----> 8     plt.imshow(image_local[z, c, :, :])
      9     plt.tight_layout()
     10     fig.canvas.flush_events()

IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed
```

I uploaded successfully a tiff, but it has 4 indices, and the following cell crashed ^^^
Screenshot 2024-04-17 at 15 03 10

**Comment by pwalczysko** [comment]
whatever tiff I am trying to upload, it has always ``image_local.shape`` as (xxx, xxx, 4) == will always crash. Not sure why, few of my images are created by OMERO.figure (export option).

the only image which works is the B1...tiff one which I picked in my local checkout of this repo.

**Comment by pwalczysko** [comment]
the Reading images notebook works fine on M1 and Colab. 

But the cell just after upload of tif feature in Colab seems to crash on the inexpected image dimensions. Possibly the cell is too specific for the B1...tif ?

**Review by pwalczysko — CHANGES_REQUESTED** [review]
Please address https://github.com/ome/EMBL-EBI-imaging-course-04-2024/pull/9#issuecomment-2061645381

**Comment by jburel** [comment]
@pwalczysko done

**Comment by pwalczysko** [comment]
> @pwalczysko done

Yes, now it does not crash. Unfotunately though, for all the other images except the B1...tif the display of the image is not true, it just displays something like y-axis instead of the image as checked locally, see screenshot below.
I guess this is because there is a dimension mismatch. I also tried to create a TIF using Fiji (possibly a way which participants might choose) and again, this tif uploads, but it looks like below (it is highlighted wrongly as having hundreds of z-sections.
Screenshot 2024-04-17 at 18 13 12

**Comment by jburel** [comment]
This really depends on the image I used images from https://downloads.openmicroscopy.org/images/TIFF/ and no problem
Unfortunately I don't know the order for the axis i.e. is z first dimension in the array. This really depends on the image

**Comment by jburel** [comment]
Merging so I can move forward and avoid conflict.
I can always go back to it

**Pull request merged**
